version: "3"

services:
  backend:
    build: ./
    container_name: quiz_container
    working_dir: /quizzz
    restart: always
    command:
      - ./commands/start_server.sh
    ports:
      - ${LOCAL_PORT}:${WSGI_PORT}
    volumes:
      - ./src:/quizzz/src
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5000:80"
    volumes:
      - pgadmin_data:"/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pg_data: { }
  pgadmin_data: { }
