version: "3"

services:
  backend:
    build: ./
    container_name: quiz_container
    working_dir: /quizzz
    restart: always
    command:
      - ./commands/start_server_${MODE}.sh
    ports:
      - ${LOCAL_PORT}:${WSGI_PORT}
    volumes:
      - ./src:/quizzz/src
      - static_content:/quizzz/src/static
      - media_content:/quizzz/src/media
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5000:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  mongodb:
    image: mongo:3-stretch
    ports:
      - 27017:27017
    container_name: mongo_db_container
    command: [ "--bind_ip_all", "--smallfiles" ]
    volumes:
      - mongo_data:/data/db
    restart: always
    env_file:
      - .env

  mongoadmin:
    image: mongo-express
    restart: always
    container_name: mongo_admin_container
    ports:
      - 8091:8081
    env_file:
      - .env
    links:
      - mongodb
    depends_on:
      - mongodb

  nginx:
    image: nginx:1.19
    volumes:
      - static_content:/quizzz/src/static
      - media_content:/quizzz/src/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      - backend

  #  rabbitmq:
  #    image: rabbitmq:3.8-management-alpine
  #    env_file:
  #      - .env
  #    restart: on-failure

  redis:
    image: redis
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - backend

  celery:
    build: ./
    command:
      - ./commands/start_celery.sh
    restart: always
    volumes:
      - ./src:/quizzz
      - ./commands:/quizzz/commands
    env_file:
      - .env
    depends_on:
      - redis
      - backend

volumes:
  pg_data: { }
  pgadmin_data: { }
  mongo_data: { }
  static_content: { }
  media_content: { }